targets:
  $default:
    builders:
      freezed:
        options:
          runs_before:
            - hive_generator
      hive_generator:
        options:
          runs_before:
            - auto_route_generator
